// Generated by ForUI CLI; regenerate this theme instead of hand-applying lint fixes.
// ignore_for_file: type=lint

part of 'generated_forui_theme.dart';

final FColors lightColors = FColors(
  brightness: .light,
  systemOverlayStyle: .dark,
  barrier: Color(0x33000000),
  background: Color(0xFFFFFFFF),
  foreground: Color(0xFF0A0A0A),
  primary: Color(0xFF171717),
  primaryForeground: Color(0xFFFAFAFA),
  secondary: Color(0xFFF5F5F5),
  secondaryForeground: Color(0xFF171717),
  muted: Color(0xFFF5F5F5),
  mutedForeground: Color(0xFF737373),
  destructive: Color(0xFFE7000B),
  destructiveForeground: Color(0xFFFAFAFA),
  error: Color(0xFFE7000B),
  errorForeground: Color(0xFFFAFAFA),
  card: Color(0xFFFFFFFF),
  border: Color(0xFFE5E5E5),
);

final FColors darkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: .light,
  barrier: Color(0x7A000000),
  background: Color(0xFF0A0A0A),
  foreground: Color(0xFFFAFAFA),
  primary: Color(0xFFE5E5E5),
  primaryForeground: Color(0xFF171717),
  secondary: Color(0xFF262626),
  secondaryForeground: Color(0xFFFAFAFA),
  muted: Color(0xFF262626),
  mutedForeground: Color(0xFFA1A1A1),
  destructive: Color(0xFFFF6467),
  destructiveForeground: Color(0xFFFAFAFA),
  error: Color(0xFFFF6467),
  errorForeground: Color(0xFFFAFAFA),
  card: Color(0xFF171717),
  border: Color(0x1AFFFFFF),
);
